# Generated by Django 5.0.2 on 2024-06-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_time_create_project_time_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='git_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL address'),
        ),
    ]
