# Generated by Django 5.0.2 on 2024-06-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_image_repository'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='projects/images/')),
            ],
        ),
    ]
