# Generated by Django 5.0.2 on 2024-06-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_mycv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyCv',
            new_name='CV',
        ),
    ]
