# Generated by Django 5.0.2 on 2024-06-16 15:18

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_image_projectimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CV',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project'},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'verbose_name': 'Images (for Project)', 'verbose_name_plural': 'Images (for Project)'},
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to=projects.models.project_image_upload_to),
        ),
        migrations.DeleteModel(
            name='Repository',
        ),
    ]
