# Generated by Django 5.0.2 on 2024-06-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_alter_messages_contact_us_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
