# Generated by Django 5.0.2 on 2024-06-27 12:20

import cv.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_alter_personalinfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{1,15}$', message='Phone number must be between 1 to 15 digits.'), cv.models.validate_phone_number]),
        ),
    ]
