# Generated by Django 5.0.2 on 2024-06-27 12:22

import cv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_alter_personalinfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='first_name',
            field=models.CharField(max_length=50, validators=[cv.models.validate_name_format], verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='last_name',
            field=models.CharField(max_length=50, validators=[cv.models.validate_name_format], verbose_name='Last name'),
        ),
    ]
