# Generated by Django 5.0.2 on 2024-06-27 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_alter_personalinfo_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{1,15}$', message='Phone number must be between 1 to 15 digits.')]),
        ),
    ]
