# Generated by Django 5.0.2 on 2024-06-28 12:14

import cv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_alter_personalinfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='contact_us_msg',
            field=models.TextField(max_length=250, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='phone',
            field=models.CharField(max_length=15, validators=[cv.models.validate_phone_number]),
        ),
    ]
