# Generated by Django 5.0.2 on 2024-07-03 11:10

import cv.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_alter_messages_contact_us_msg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=35, validators=[cv.validators.validate_name_format], verbose_name='Full name')),
                ('email', models.EmailField(blank=True, max_length=25, null=True, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=11, validators=[cv.validators.validate_phone_number])),
                ('methods', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('email', 'Email'), ('phone_call', 'Phone call'), ('any', 'Any')], default='any', max_length=20, verbose_name='Preferred Contact Method')),
                ('message', models.TextField(blank=True, max_length=250, null=True, verbose_name='Message')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
