# Generated by Django 5.0.2 on 2024-07-04 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_contactus_delete_messages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cv',
            options={'verbose_name_plural': 'CV'},
        ),
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'verbose_name_plural': 'Personal info'},
        ),
    ]
